spring.datasource.url=jdbc:mysql://localhost:3306/app?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root

spring.credit-gate.url=http://localhost:9999
spring.payment-gate.url=http://localhost:9999/payment
org.gradle.jvmargs=-Dfile.encoding=UTF-8