version: '3.7'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql_aqa
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql

  postgres:
    image: postgres:13
    container_name: postgres_aqa
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

  gate-simulator:
    build:
      context: ./gate-simulator
    container_name: gate_simulator
    ports:
      - "9999:9999"