# URL ??????????
app.url=http://localhost:8080

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/app
spring.datasource.username=user
spring.datasource.password=pass

# PostgreSQL
spring.datasource.postgres.url=jdbc:postgresql://localhost:5432/app
spring.datasource.postgres.username=user
spring.datasource.postgres.password=pass

# ?????????? ????????
payment.gate.url=http://localhost:9999/payment
credit.gate.url=http://localhost:9999/credit
spring.credit-gate.url=http://localhost:9999